### ISSUE TITLE
Unusable players can't be removed

### ISSUE THREAD

**Issue by noxan** [pichfl/decknamen#14]
Somehow when I joined with Chrome it added two players instead of one. I could only control one, there was no way for anybody to remove the unusable player, but it remained in game for the whole time.

How about having an option to remove other players? At least for the leads or for the person who created the session

**Comment by pichfl** [comment]
The list is updating life, do dropping out mid game will lead to problems here. 

Propose solution: Make a copy the list of players that started the game.
