### ISSUE TITLE
Obfuscate socket communication?

### ISSUE THREAD

**Issue by pichfl** [pichfl/decknamen#24]
Right now it is possible to read the game state in plain text which makes it easy to cheat by simply looking at the socket communication which sends around the game state (boooh to those who try that). Running a simple cypher could help to stop that. of course it can still be decoded, but it involves an extra step. ¯\\\_(ツ)\_/¯ 

Any opinions?

**Comment by GianniCarlo** [comment]
hmmmm I don't think this will be an issue for predefined parties 🤔. Once there's a random party feature or something like that, then it could be an issue

**Comment by pichfl** [comment]
Good point. Closing for now, people need to stay away from the Ember Inspector for a bit 😄
